### ISSUE TITLE
Add Folders to the Grenades Tab

### ISSUE THREAD

**Issue by PXLCoarl** [JH1ller/csgo-stratbook#146]
Would it be possible to add folders to the grenades tab, so one can sort the grenades into categories?

**Comment by JH1ller** [comment]
Hi, thanks for the suggestion. Could you elaborate and maybe give an example?

**Comment by PXLCoarl** [comment]
![suggestion](https://user-images.githubusercontent.com/86272287/158073105-304e7108-1e03-4308-b5eb-2023b183a06c.png)

I made a quick visual how id imagine it to work, basically just the ability to sort the uploaded files into categories that you can define yourself, because currently, atleast for us, the stratbook can get super messy and unorganized like this:

![currently](https://user-images.githubusercontent.com/86272287/158073153-4ae0d53f-32f4-4014-8ece-70b9aec310a4.png)

**Comment by JH1ller** [comment]
Thank you for the mockup, that clears it up. I'm not sure if a folder structure like you propose would be the best way here. 
For CT / T side I can highly recommend using the filters on the bottom right.
For things like "Situational" what would you think about "Badges" or "Tags" that you can add to a utility?
These would be visible on the utility tile and all badges would also show at the top to allow for quick filtering by badge.
Kind of like this:

![badge mockup](https://user-images.githubusercontent.com/15629818/158761914-e91ab964-337f-463b-a8af-5e7cdd98cb5e.png)

**Comment by PXLCoarl** [comment]
Would it be possible then to add filters for the Positions? Like A, B, Mid eg?

**Comment by JH1ller** [comment]
Yes, that would be possible.
