### ISSUE TITLE
4:3 image is zoomed instead of black bars

### ISSUE THREAD

**Issue by pfuhlert** [JH1ller/csgo-stratbook#172]
Hi,

nice tool. We start to like it a lot! When I upload an image from csgo (I play 4:3) then it is zoomed in when I open the screenshot on stratbook when I view it on my 16:9 monitor. This way I cannot see the edges of the screen. So maybe instead of zooming in, fill with black bars? Example below:

old:
![old](https://user-images.githubusercontent.com/6412273/181589416-a0345d87-5a65-4356-9a26-b93d40ce529a.png)

new:
![new](https://user-images.githubusercontent.com/6412273/181589780-a4726be6-1f11-484e-a680-61c33d411e45.png)

**Comment by JH1ller** [comment]
Hm, makes sense. I will adjust it when I find the time.
