### ISSUE TITLE
Ability to Link Utility in Strat Editor

### ISSUE THREAD

**Issue by bannert1337** [JH1ller/csgo-stratbook#228]
**Is your feature request related to a problem? Please describe.**
Currently, when creating strategies in the strat editor, there's no straightforward way to directly link utilities. This makes it less efficient to reference specific utility usage in a strategy.

**Describe the solution you'd like**
Add the ability to link utilities directly in the strat editor. This could be achieved by a special markup (similar to the '@' for mentioning teammates), or by providing a dropdown list of utilities when editing a strategy. Clicking on the linked utility should take the user to the details of that utility.

**Describe alternatives you've considered**
As an alternative, users could manually write the name of the utility in the strategy, but this doesn't provide the same level of interactivity and ease of access to the utility details.

**Additional context**
This feature would enhance the utility of the strat editor by making it easier to incorporate specific utilities into strategies. It would also make strategies more interactive and easier to understand, as users could directly access the details of a utility from the strategy itself.

**Comment by JH1ller** [comment]
This is already a thing :)
Just press '#' just like '@' to mention teammates.
