### ISSUE TITLE
Unable to start "node-api" container. 

### ISSUE THREAD

**Issue by andre-luca** [JH1ller/csgo-stratbook#262]
Hey there I found this great project. Trying hard to get it running on my local machine. While trying to run server and client through docker-compose I found an issue with the node-api container failing to start.

> 2023-09-17 10:22:26 
> 2023-09-17 10:22:26 > csgo-stratbook-server@2.0.0 serve /usr/src/app/server
> 2023-09-17 10:22:26 > cross-env NODE_ENV=development tsnd --respawn --inspect=0.0.0.0:9229 --files -r tsconfig-paths/register src/index.ts
> 2023-09-17 10:22:26 
> 2023-09-17 10:22:27 [INFO] 08:22:27 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 4.9.5)
> 2023-09-17 10:22:27 Debugger listening on ws://0.0.0.0:9229/3f9506aa-83ca-4c0e-93ba-271585706699
> 2023-09-17 10:22:27 For help, see: https://nodejs.org/en/docs/inspector
> 2023-09-17 10:22:31 Compilation error in /usr/src/app/server/src/sockets/index.ts
> 2023-09-17 10:22:31 [ERROR] 08:22:31 ⨯ Unable to compile TypeScript:
> 2023-09-17 10:22:31 src/sockets/index.ts(23,7): error TS2322: Type 'undefined' is not assignable to type 'Promise<unknown>'.
> 2023-09-17 10:22:31 src/sockets/index.ts(87,9): error TS2322: Type 'undefined' is not assignable to type 'Promise<unknown>'.
> 2023-09-17 10:22:31

If I try to start the server without docker with the npm run serve command after npm install and the .env setup, I'm getting different types of errors.

>  10:29:07 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 4.9.5)
> Debugger listening on ws://0.0.0.0:9229/2ddc518d-b0de-4a89-9ea0-e35d076f235c
> For help, see: https://nodejs.org/en/docs/inspector
> Error: Illegal arguments: undefined, string
>     at bcrypt.hashSync (/Users/andreluca/Developer/csgo-stratbook/server/node_modules/bcryptjs/dist/bcrypt.js:189:19)
>     at Object.<anonymous> (/Users/andreluca/Developer/csgo-stratbook/server/src/index.ts:150:23)
>     at Module._compile (node:internal/modules/cjs/loader:1256:14)
>     at Module._compile (/Users/andreluca/Developer/csgo-stratbook/server/node_modules/source-map-support/source-map-support.js:568:25)
>     at Module.m._compile (/private/var/folders/5b/yq4b_sbx73580ksmz0725pv40000gn/T/ts-node-dev-hook-5639529618359884.js:69:33)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>     at require.extensions..jsx.require.extensions..js (/private/var/folders/5b/yq4b_sbx73580ksmz0725pv40000gn/T/ts-node-dev-hook-5639529618359884.js:114:20)
>     at require.extensions.<computed> (/private/var/folders/5b/yq4b_sbx73580ksmz0725pv40000gn/T/ts-node-dev-hook-5639529618359884.js:71:20)
>     at Object.nodeDevHook [as .ts] (/Users/andreluca/Developer/csgo-stratbook/server/node_modules/ts-node-dev/lib/hook.js:63:13)
>     at Module.load (node:internal/modules/cjs/loader:1119:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:960:12)
>     at Module.require (node:internal/modules/cjs/loader:1143:19)
>     at require (node:internal/modules/cjs/helpers:121:18)
>     at Object.<anonymous> (/Users/andreluca/Developer/csgo-stratbook/server/node_modules/ts-node-dev/lib/wrap.js:104:1)
>     at Module._compile (node:internal/modules/cjs/loader:1256:14)
>     at Module._compile (/Users/andreluca/Developer/csgo-stratbook/server/node_modules/source-map-support/source-map-support.js:568:25)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>     at Object.require.extensions..jsx.require.extensions..js (/private/var/folders/5b/yq4b_sbx73580ksmz0725pv40000gn/T/ts-node-dev-hook-5639529618359884.js:95:24)
>     at Module.load (node:internal/modules/cjs/loader:1119:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:960:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:23:47
> [ERROR] 10:29:11 Error: Illegal arguments: undefined, string

Any suggestions for me to get this up and running?

Thanks in advance.

**Comment by JH1ller** [comment]
Hey there, I've updated the Dockerfiles now, they had an old nodejs version that we're not supporting anymore.

Here is the PR: #265

Could you try it again?

**Comment by andre-luca** [comment]
Awesome, fixed it for me 👍
